version: "3.3"

networks:
    frontend:
    backend:     

volumes:
    wordpress:
    maria_db:

services:
    db:
        image: mariadb:10.5.2-bionic
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: manish
            MYSQL_PASSWORD: redhat
            MYSQL_ROOT_PASSWORD: redhat
        volumes:
            - maria_db:/var/lib/mysql
        networks: 
            - backend
    adminer:
        image: adminer
        depends_on: 
            - db
        ports:
            - 8001:8080
        networks:
            - frontend
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db
        ports:
            - 8002:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: redhat
        networks:
            - frontend
            - backend
  
